In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA, FactorAnalysis, FastICA
from sklearn import preprocessing
import matplotlib.pyplot as plt
import os
%matplotlib inline

pd.set_option('display.max_columns', None)

In [2]:
df=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data',na_values='?',
               header=None,index_col=0)#,names=['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name'])
df=df.loc[:,:5]
df=df.dropna(how='any')
df.head()

1  2  3  4  5
0                     
1000025  5  1  1  1  2
1002945  5  4  4  5  7
1015425  3  1  1  1  2
1016277  6  8  8  1  3
1017023  4  1  1  3  2

In [3]:
df.describe()

1           2           3           4           5
count  699.000000  699.000000  699.000000  699.000000  699.000000
mean     4.417740    3.134478    3.207439    2.806867    3.216023
std      2.815741    3.051459    2.971913    2.855379    2.214300
min      1.000000    1.000000    1.000000    1.000000    1.000000
25%      2.000000    1.000000    1.000000    1.000000    2.000000
50%      4.000000    1.000000    1.000000    1.000000    2.000000
75%      6.000000    5.000000    5.000000    4.000000    4.000000
max     10.000000   10.000000   10.000000   10.000000   10.000000

## 一、标准化（Z-Score）  

公式为：(X-mean)/std  计算时对每个属性/每列分别进行。

In [4]:
from sklearn import preprocessing
standard_scaler = preprocessing.StandardScaler()

standard_scaler.fit(df)
standard_scaler.transform(df)

array([[ 0.20693572, -0.69999505, -0.74329904, -0.63324716, -0.54956136],
       [ 0.20693572,  0.28384518,  0.2668747 ,  0.76862067,  1.71010564],
       [-0.50386559, -0.69999505, -0.74329904, -0.63324716, -0.54956136],
       ..., 
       [ 0.20693572,  2.25152563,  2.28722218,  0.06768675,  1.71010564],
       [-0.14846494,  1.59563215,  0.94032386,  0.41815371, -0.09762796],
       [-0.14846494,  1.59563215,  1.61377302,  0.76862067,  0.35430544]])

## 0-1标准化
使用这种方法的目的包括：

1、对于方差非常小的属性可以增强其稳定性。

2、维持稀疏矩阵中为0的条目。

In [5]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

min_max_scaler.fit(df)
min_max_scaler.transform(df)

array([[ 0.44444444,  0.        ,  0.        ,  0.        ,  0.11111111],
       [ 0.44444444,  0.33333333,  0.33333333,  0.44444444,  0.66666667],
       [ 0.22222222,  0.        ,  0.        ,  0.        ,  0.11111111],
       ..., 
       [ 0.44444444,  1.        ,  1.        ,  0.22222222,  0.66666667],
       [ 0.33333333,  0.77777778,  0.55555556,  0.33333333,  0.22222222],
       [ 0.33333333,  0.77777778,  0.77777778,  0.44444444,  0.33333333]])

## 三、正则化（Normalization）
每个样本变成单位范数

In [6]:
from sklearn import preprocessing
normalizer = preprocessing.Normalizer(norm='l2')

normalizer.fit(df)
normalizer.transform(df)

array([[ 0.88388348,  0.1767767 ,  0.1767767 ,  0.1767767 ,  0.35355339],
       [ 0.43685203,  0.34948162,  0.34948162,  0.43685203,  0.61159284],
       [ 0.75      ,  0.25      ,  0.25      ,  0.25      ,  0.5       ],
       ..., 
       [ 0.29721915,  0.5944383 ,  0.5944383 ,  0.17833149,  0.41610681],
       [ 0.33686077,  0.67372154,  0.50529115,  0.33686077,  0.25264558],
       [ 0.29408585,  0.5881717 ,  0.5881717 ,  0.36760731,  0.29408585]])