In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data

mnist=input_data.read_data_sets('../../haha')

sess=tf.Session()

Extracting ../../haha\train-images-idx3-ubyte.gz
Extracting ../../haha\train-labels-idx1-ubyte.gz
Extracting ../../haha\t10k-images-idx3-ubyte.gz
Extracting ../../haha\t10k-labels-idx1-ubyte.gz


In [2]:
in_units=784
h1_units=300
w1=tf.Variable(tf.truncated_normal(shape=(in_units,h1_units),stddev=0.1))
b1=tf.Variable(tf.zeros([h1_units]))
w2=tf.Variable(tf.zeros(shape=(h1_units,10)))
b2=tf.Variable(tf.zeros([10]))

In [3]:
x=tf.placeholder(tf.float32,[None,in_units])
y_=tf.placeholder(tf.float32,shape=(None,10))
keep_prob=tf.placeholder(tf.float32)#训练时小于1，预测时等于1，所以还是用placeholder

In [4]:
hidden1=tf.nn.relu(tf.matmul(x,w1)+b1)
hidden1_drop=tf.nn.dropout(hidden1,keep_prob)# 注意！
y=tf.nn.softmax(tf.matmul(hidden1_drop,w2)+b2)

In [5]:
cross_entropy=tf.reduce_mean(-tf.reduce_sum(y_*tf.log(y),reduction_indices=[1]))
train_step=tf.train.AdagradOptimizer(learning_rate=0.3).minimize(cross_entropy)

In [6]:
sess.run(tf.global_variables_initializer())
STEPS=5000
for i in range(STEPS):
    batch_xs,batch_ys=mnist.train.next_batch(100)
    batch_ys1=np.zeros((batch_ys.shape[0],10))#数据格式恶心了
    for index,value in enumerate(batch_ys):
        batch_ys1[index,value]=1
    sess.run(train_step,feed_dict={x:batch_xs,y_:batch_ys1,keep_prob:0.75232})#keep_prob
    if i%500==0:
        print(sess.run(cross_entropy,feed_dict={x:batch_xs,y_:batch_ys1,keep_prob:0.75232}))
    

2.47829
0.156253
0.0564876
0.0177163
0.0281413
0.0114876
0.015493
0.0384636
0.0264609
0.0134964


In [20]:
y_test_predict=sess.run(y,feed_dict={x:mnist.test.images,keep_prob:1})
import sklearn.metrics as metrics
print('test\n',metrics.confusion_matrix(mnist.test.labels,y_test_predict.argmax(axis=1)))

test
 [[ 974    1    2    0    0    0    1    1    1    0]
 [   0 1126    5    0    0    1    2    0    1    0]
 [   4    0 1019    1    1    0    0    5    2    0]
 [   0    0    9  994    0    1    0    2    3    1]
 [   1    1    8    1  956    0    2    3    2    8]
 [   2    0    0   14    0  862    4    2    7    1]
 [   8    3    1    1    2    2  938    0    3    0]
 [   2    4   14    1    1    0    0 1000    2    4]
 [   4    1    4    1    1    0    1    2  958    2]
 [   4    4    1    5    7    1    0    7    3  977]]
